# Generated by Django 4.0 on 2022-01-02 18:45

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'Client'},
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default='1983-04-14', verbose_name='Date de naissance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='FR', max_length=150, verbose_name='Ville'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(default='FR', max_length=2, verbose_name='Pays'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='0123456789', max_length=150, verbose_name='Téléphone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='postal_code',
            field=models.CharField(default='83260', max_length=15, verbose_name='Code Postal'),
            preserve_default=False,
        ),
    ]
